name: cellpose_srh
dependencies:
    - python<=3.7
    - pip
    - jupyter
    - xmltodict
    - pandas
    - seaborn
    - mkl=2019.3
    - numpy
    - scikit-image
    - numba>=0.43.1
    - pyqt
    - scipy
    - matplotlib
    - zarr
    - lxml
    - scipy
    - autopep8
    - pip:
          - mxnet-mkl
          - opencv_python
          - pyqtgraph
          - natsort
          - google-cloud-storage
          - tqdm
          - czifile
          - apeer-ometiff-library
          - apeer-dev-kit
          - napari
          - aicsimageio
          - MightyMosaic
          - silence-tensorflow
          - cellpose
          - progressbar2
# conda env create -f environment_srh.yml
# conda env update --name cellpose_srh --file environment_srh.yml
